apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
labels:
- includeSelectors: true
  pairs:
    org: acmeCorporation
    variant: production
commonAnnotations:
  note: Hello, I am production!
resources:
- ../../base
patches:
- path: deployment.yaml
