apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello
metadata:
  name: arbitrary

# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- configMap.yaml
